#include "Insertion Sort.hpp"
#include "Bubble Sort.hpp"
#include "Selection Sort.hpp"
#include "Merge Sort.hpp"
#include "Quick Sort.hpp"
#include "DNF Sort.hpp"
#include "Count Sort.hpp"
#include "Wave Sort.hpp"